/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.sprint1opcao2;

/**
 *
 * @author HP x360
 */
public class PrecoSistemaOperacional extends javax.swing.JFrame {

    /**
     * Creates new form PrecoSistemaOperacional
     */
    public PrecoSistemaOperacional() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        lbComputadores = new javax.swing.JLabel();
        tfComputadores = new javax.swing.JTextField();
        lbPools = new javax.swing.JLabel();
        tfPools = new javax.swing.JTextField();
        lbWindows = new javax.swing.JLabel();
        tfWindows = new javax.swing.JTextField();
        lbLinux = new javax.swing.JLabel();
        tfLinux = new javax.swing.JTextField();
        lbMacos = new javax.swing.JLabel();
        tfMacos = new javax.swing.JTextField();
        btCalculo = new javax.swing.JButton();
        lbTexto = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTitulo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(204, 0, 204));
        lbTitulo.setText("mineHash - Você Minerando e a gente Monitorando");

        lbComputadores.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbComputadores.setForeground(new java.awt.Color(51, 0, 255));
        lbComputadores.setText("Computadores : ");

        tfComputadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfComputadoresActionPerformed(evt);
            }
        });

        lbPools.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbPools.setForeground(new java.awt.Color(51, 0, 255));
        lbPools.setText("Pools :  ");

        lbWindows.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbWindows.setForeground(new java.awt.Color(51, 0, 255));
        lbWindows.setText("Windows : ");

        lbLinux.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lbLinux.setForeground(new java.awt.Color(51, 0, 255));
        lbLinux.setText("Linux : ");

        lbMacos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbMacos.setForeground(new java.awt.Color(51, 0, 255));
        lbMacos.setText("MacOs : ");

        btCalculo.setBackground(new java.awt.Color(102, 0, 102));
        btCalculo.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btCalculo.setForeground(new java.awt.Color(255, 255, 255));
        btCalculo.setText("Cálculo Orçamento");
        btCalculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalculoActionPerformed(evt);
            }
        });

        lbTexto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTexto.setText("Resposta aqui :  ");

        lbTotal.setText("_______________________________");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbComputadores)
                                .addGap(18, 18, 18)
                                .addComponent(tfComputadores, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbWindows)
                                    .addComponent(lbPools)
                                    .addComponent(lbLinux)
                                    .addComponent(lbMacos))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPools, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfWindows, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfLinux, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfMacos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(lbTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbComputadores)
                    .addComponent(tfComputadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPools))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbWindows)
                    .addComponent(tfWindows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLinux)
                    .addComponent(tfLinux, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMacos)
                    .addComponent(tfMacos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btCalculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTexto)
                    .addComponent(lbTotal))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCalculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalculoActionPerformed
        // TODO add your handling code here:
        
        Integer computadores = Integer.valueOf(tfComputadores.getText());
        Integer pools = Integer.valueOf(tfPools.getText());
        Integer windows = Integer.valueOf(tfWindows.getText());
        Integer linux = Integer.valueOf(tfLinux.getText());
        Integer macos = Integer.valueOf(tfMacos.getText());
        
        Integer qtdsos = windows + linux + macos;
        
        Double soma1 = windows *  29.90;
        Double soma2 = linux * 39.90;
        Double soma3 = macos * 49.90;
        
        Double somaTotal = soma1 + soma2 + soma3;
        
        if (computadores > qtdsos || computadores < qtdsos){
            String resultado = String.format(
            "Valores incorretos");
            lbTotal.setText(resultado); 
        } else {
            String resultado1 = String.format(
            "Total por mês: R$%.2f", somaTotal);
            lbTotal.setText(resultado1);
        }
    }//GEN-LAST:event_btCalculoActionPerformed

    private void tfComputadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfComputadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfComputadoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrecoSistemaOperacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrecoSistemaOperacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrecoSistemaOperacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrecoSistemaOperacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrecoSistemaOperacional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalculo;
    private javax.swing.JLabel lbComputadores;
    private javax.swing.JLabel lbLinux;
    private javax.swing.JLabel lbMacos;
    private javax.swing.JLabel lbPools;
    private javax.swing.JLabel lbTexto;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbWindows;
    private javax.swing.JTextField tfComputadores;
    private javax.swing.JTextField tfLinux;
    private javax.swing.JTextField tfMacos;
    private javax.swing.JTextField tfPools;
    private javax.swing.JTextField tfWindows;
    // End of variables declaration//GEN-END:variables
}
